# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default" # options: air, aqua, contrast, dark, dirt, neon, mint, plum, sunrise

# Site Settings
title: "Adaptique"
subtitle: # site tagline that appears below site title
name: "Adaptique"
description: "Your site description."
url: "https://code.adaptique.io"
baseurl: "https://code.adaptique.io"

# Site Author
author:
  name: "Bob Tribit"
  avatar: # path to your avatar image
  bio: "Overly pedantic auto-didactic dilettante"
  location: "Remote"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/adaptique"
